import os

import requests
from pydantic import BaseModel, Field

from depsafe.tool.utils.github import get_repo_info


class PRCreateResult(BaseModel):
    """PR 创建结果"""

    success: bool = Field(..., description="PR 是否创建成功")
    pr_url: str | None = Field(None, description="创建成功时返回的 PR 网页链接")
    pr_number: int | None = Field(None, description="创建成功时返回的 PR 编号")
    error: str | None = Field(None, description="创建失败时的错误信息")


def _build_pr_body(
    cve_id: str,
    pkg_name: str,
    old_version: str,
    new_version: str,
    priority: str,
    reason: str,
    reachability: str,
    test_skipped: bool,
    breaking_changes: list[str] | None,
) -> str:
    """拼装结构化 PR Body"""
    lines = [
        "## Security Vulnerability Fix",
        "",
        f"This PR automatically upgrades `{pkg_name}` to resolve **{cve_id}**.",
        "",
        "### Vulnerability Details",
        "",
        f"- **CVE**: {cve_id}",
        f"- **Package**: `{pkg_name}`",
        f"- **Version Change**: `{old_version}` -> `{new_version}`",
        f"- **Reachability**: `{reachability}`",
        "",
        "### Priority Assessment",
        "",
        f"- **Priority**: **{priority}**",
        f"- **Reason**: {reason}",
        "",
    ]
    if test_skipped:
        lines.extend(
            [
                "### Test Execution Warning",
                "",
                "> Automated tests were **skipped** or unavailable during the verification phase. ",
                "> Please review the changes carefully before merging.",
                "",
            ]
        )
    if breaking_changes:
        lines.extend(
            [
                "### Breaking Changes Detected",
                "",
                "The following breaking changes were identified in the target version's changelog. ",
                "**Manual review is required before merging.**",
                "",
            ]
        )
        for change in breaking_changes:
            lines.append(f"- {change}")
        lines.append("")
    lines.extend(
        [
            "---",
            "",
            "_Generated by DepSafe Automated Security Agent_",
        ]
    )
    return "\n".join(lines)


def _ensure_labels(token: str, owner: str, repo: str, labels: list[str]) -> str | None:
    """
    确保仓库中存在指定标签，缺失则自动创建。

    GitHub 创建 PR 时会静默丢弃不存在的标签，因此必须先补建。
    201（创建成功）与 422（已存在）均视为正常。

    Returns:
        错误信息；成功返回 None。
    """
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    for label in labels:
        try:
            response = requests.post(
                f"https://api.github.com/repos/{owner}/{repo}/labels",
                json={"name": label, "color": "d73a4a", "description": "Applied by DepSafe automated fix"},
                headers=headers,
                timeout=15,
            )
            if response.status_code not in (201, 422):
                return f"Ensure label '{label}' failed: {response.status_code} {response.text[:200]}"
        except requests.RequestException as e:
            return f"Ensure label '{label}' failed: {type(e).__name__}: {e}"
    return None


def _apply_labels(token: str, owner: str, repo: str, pr_number: int, labels: list[str]) -> str | None:
    """
    PR 创建后通过 Issues API 追加标签。

    实测 GitHub 的 POST/PATCH /pulls 会静默丢弃 labels 字段（细粒度 PAT），
    唯一可靠的打标签方式是这个 add-labels 端点。

    Returns:
        错误信息；成功返回 None。
    """
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    try:
        response = requests.post(
            f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/labels",
            json={"labels": labels},
            headers=headers,
            timeout=15,
        )
        if response.status_code != 200:
            return f"Apply labels {labels} to PR #{pr_number} failed: {response.status_code} {response.text[:200]}"
    except requests.RequestException as e:
        return f"Apply labels {labels} to PR #{pr_number} failed: {type(e).__name__}: {e}"
    return None


def _enable_auto_merge(token: str, pr_node_id: str) -> tuple[bool, str | None]:
    """
    通过 GraphQL API 开启 Auto-merge。
    注意：前提是仓库 Settings 中已开启 "Allow auto-merge"。
    """
    graphql_url = "https://api.github.com/graphql"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    # mergeMethod 可选: MERGE, SQUASH, REBASE
    query = """
    mutation EnableAutoMerge($pullRequestId: ID!) {
      enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: SQUASH}) {
        pullRequest {
          autoMergeRequest {
            enabledAt
          }
        }
      }
    }
    """
    payload = {"query": query, "variables": {"pullRequestId": pr_node_id}}
    try:
        response = requests.post(graphql_url, json=payload, headers=headers, timeout=15)
        response.raise_for_status()
        data = response.json()
        if "errors" in data:
            msgs = "; ".join(e.get("message", str(e)) for e in data["errors"])
            return False, f"GraphQL errors: {msgs}"
        return True, None
    except Exception as e:
        return False, f"{type(e).__name__}: {e}"


def create_github_pr(
    title: str,
    head_branch: str,
    base_branch: str,
    cve_id: str,
    pkg_name: str,
    old_version: str,
    new_version: str,
    priority: str,
    reason: str,
    reachability: str,
    test_skipped: bool,
    breaking_changes: list[str] | None = None,
) -> PRCreateResult:
    """
    创建安全修复 Pull Request。
    P0: 普通 PR + Auto-merge
    P1: Draft PR (含 breaking changes)
    P2: 普通 PR
    """
    # 1. 获取 GitHub Token
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        return PRCreateResult(success=False, error="GITHUB_TOKEN environment variable is not set")
    # 2. 解析仓库信息
    try:
        owner, repo = get_repo_info()
    except Exception as e:
        return PRCreateResult(success=False, error=f"Failed to get repo info: {type(e).__name__}: {e}")
    # 3. 拼装 Body
    body = _build_pr_body(
        cve_id=cve_id,
        pkg_name=pkg_name,
        old_version=old_version,
        new_version=new_version,
        priority=priority,
        reason=reason,
        reachability=reachability,
        test_skipped=test_skipped,
        breaking_changes=breaking_changes,
    )
    # 4. 确定 Labels 和 Draft 状态
    is_draft = priority == "P1"
    base_labels = ["security"]
    if priority == "P0":
        base_labels.append("auto-merge")
    elif priority == "P1":
        base_labels.append("needs-review")
    # 5. 确保标签存在（GitHub 会静默丢弃不存在的标签）
    label_errors: list[str] = []
    if ensure_err := _ensure_labels(token, owner, repo, base_labels):
        label_errors.append(ensure_err)
    # 6. 调用 REST API 创建 PR
    api_url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {
        "title": title,
        "body": body,
        "head": head_branch,
        "base": base_branch,
        "draft": is_draft,
        "labels": base_labels,
    }
    try:
        response = requests.post(api_url, json=payload, headers=headers, timeout=30)
        response.raise_for_status()
        data = response.json()
        pr_number = data["number"]
        pr_url = data["html_url"]
        pr_node_id = data.get("node_id")
        # 7. 创建后通过 Issues API 打标签（POST /pulls 的 labels 字段会被静默丢弃）
        if apply_err := _apply_labels(token, owner, repo, pr_number, base_labels):
            label_errors.append(apply_err)
        # 8. 如果是 P0，尝试通过 GraphQL 开启 Auto-merge
        if priority == "P0" and pr_node_id:
            ok, err = _enable_auto_merge(token, pr_node_id)
            if not ok:
                label_errors.append(f"Auto-merge failed: {err}")
        return PRCreateResult(
            success=True, pr_url=pr_url, pr_number=pr_number, error="; ".join(label_errors) or None
        )
    except requests.RequestException as e:
        return PRCreateResult(success=False, error=f"{type(e).__name__}: {e}")
